# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5363da4d1079c9fe98da3871cddc0a4e15f5cc17b1d0009a15b8e61aef4bf17c5ed846cd1b2391d3e1b2fa73031a792ad2996912b3a8ec6f0977ff9bfda53591

test:
  secret_key_base: 49416b8e01b46e26421c06eada4e226dd1de1057203d6887db1a7a6a5124a5ab26d7b897de9cc39ef1bdf16178b1bae1ec3e9122f3e8bfa7281e3097af2cf811

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
